# Generated by Django 2.2 on 2021-07-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('time', models.CharField(default='00:00', max_length=5)),
                ('day', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], default='Понедельник', max_length=10)),
                ('week', models.CharField(choices=[('Чётная', 'Чётная'), ('Нечётная', 'Нечётная'), ('Всегда', 'Всегда')], default='Всегда', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Список без названия.', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=16)),
                ('UID', models.CharField(max_length=64, unique=True)),
                ('CS', models.IntegerField(default=0)),
                ('level', models.CharField(default='1', max_length=8)),
                ('type', models.CharField(choices=[('Лучник', 'Лучник'), ('Маг', 'Маг'), ('Чародей', 'Чародей'), ('Жрец', 'Жрец'), ('Оборотень', 'Оборотень'), ('Убийца', 'Убийца'), ('Воин', 'Воин'), ('Друид', 'Друид')], default='Класс не указан.', max_length=16)),
            ],
        ),
    ]
