# Generated by Django 2.2 on 2021-07-26 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PWapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='guild',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='PWapp.Guild'),
        ),
    ]
