# Generated by Django 2.2 on 2021-07-26 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PWapp', '0002_auto_20210726_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PWapp.Player'),
            preserve_default=False,
        ),
    ]
