# Generated by Django 2.2 on 2021-07-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PWapp', '0005_auto_20210727_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextended',
            name='player',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='PWapp.Player'),
        ),
    ]
