# Generated by Django 2.2 on 2021-07-27 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PWapp', '0006_userextended_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='players',
            field=models.ManyToManyField(to='PWapp.Player'),
        ),
        migrations.AlterField(
            model_name='list',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
