# Generated by Django 2.2 on 2021-07-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWapp', '0007_auto_20210727_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='access',
            field=models.CharField(default='all', max_length=16),
        ),
    ]
