# Generated by Django 2.2 on 2021-07-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PWapp', '0008_list_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='access',
            field=models.CharField(choices=[('all', 'Для всех'), ('guild', 'Для гильдии'), ('me', 'Только для меня')], default='all', max_length=16),
        ),
    ]
